# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
    push:
        branches: [ master ]
    pull_request:
        branches: [ master ]

jobs:
    build:

        runs-on: ubuntu-latest

        steps:
            -   uses: actions/checkout@v2
            -   name: Weather app tests
                uses: actions/setup-java@v1
                with:
                    java-version: 11
            -   name: Run API tests
                run: mvn '-Dtest=ee.taltech.weather.api.report.*Test.java' test
            -   name: Run Console IO tests
                run: mvn '-Dtest=ee.taltech.weather.io.report.*Test' test
            -   name: Run Mock tests
                run: mvn '-Dtest=ee.taltech.weather.service.*Test' test
            -   name: Run integration tests
                run: mvn '-Dtest=ee.taltech.weather.integration.*Test' test
